#!/bin/bash

python3 /home/zoe/'GhassanGT Dropbox'/'Zoe Fowler'/Zoe/InSync/PhDResearch/Code/FedKPer/main.py --seed=1 --n_rounds=20 --partition_method="dirichlet" --partition_alpha=0.1 --dataset_name='OrganCMNIST' --model_name='medmnist' --root='/media/zoe/ssd/' --n_clients=30 --sample_ratio=0.1 --batch_size=12 --date='testing' --config_path="/config/fedkper.json"
